---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)
library(data.table)
library(RColorBrewer)

assignInNamespace("cedta.override", c(data.table:::cedta.override,"rmarkdown"), "data.table")
opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)
```

Page 1
=====================================  


Column
-------------------------------------
###  You can write something here
```{r}
inputPanel()
```

Column
-------------------------------------
### as name of this part





Page 2
=====================================

Column {.sidebar} #set a sidebar in the interface, default is on the left
-------------------------------------
### This is a sidebar
```{r}
```


Column
-------------------------------------
### This is another section

### with two parts


